language: r
sudo: true
latex: false
pandoc: false
warnings_are_errors: false

install: echo "The install step is required but does nothing now."
script:
- Rscript install_texlive.R
- Rscript -e 'tinytex::lualatex("cv.tex")'

deploy:
  provider: releases
  api_key:
    secure: A9wRgu3PjpTe0G7eDYocxiDnexMmvzn183ihlhPgmTlwl6gCVWVTYbb5UTCMS6p+x5hOhV43cFA0KBY+xVdp+AfYeJekvpCmS8J9ZQr78sUrANCCDy8vY1tglWtlfBhdQhCtX2d+P9X2qaeV56jAYf1gr7Hr9bSKHoJSxhzluEwsWFQ8gIJtqKU+wfUh+ccjVcG8/AoxFhslTNL+oqrfg8/wkNCikERpSkXPzmhJ4c/lkmd9aEaM5s3zyXXZ4XJeVsNxS2IcZiaAJGczaJPOneVqn5FhtDWuaZHj59onl0Dc73DUivOTF+7U2IUNUdZj0DNXIpXoKwi0ZNpEHyCOVkAlMDBRESclrkOOBhtyPXHXnpze8HGH0Yc0TcbcETDOzFoimx/k1fhiuEYGY4HPFeCefnteWXjw9JTvWxNVVg7dzMs5fUcrcY0wEUl53qNXQoIcaKEYqd0MJbE4U1vNnauFYpqULvxbJcpLFK2ds6wbtJm7oK3BiCBhY0f6GDM0dcdpnmpZZpHBsERZqweaMP3pBw6mMsoBGIA3rH/9ERZmCDg4yBp++7NIHcPNgdjBHh6LRHf9uj1fZT3jTctGJXnJQiKbZdrjW2wHwPE5OIknTeE4R6fqr8PFHUQ7VvI7WZ40/V8o1n+/RUNykXNnLcrsaDQgAypERLYS1NPgFNo=
 
 file:
 - ./cv.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
