language: r
sudo: true
latex: false
pandoc: false
warnings_are_errors: false
install: echo "The install step is required but does nothing now."
script:
- Rscript install_texlive.R
- Rscript -e 'tinytex::pdflatex("cv.tex", bib_engine = "biber")'
cache: packages
